import house from "/images/house.jpg";
import firstImage from "/images/firstImage.jpg";
import secondImage from "/images/secondImage.jpg";
import thirdImage from "/images/thirdImage.jpg";
import fourthImage from "/images/fourthImage.jpg";
import fifthImage from "/images/fifthImage.jpg";
import sixthImage from "/images/sixthImage.jpg";
import seventhImage from "/images/seventhImage.jpg";
import eighthImage from "/images/eighthImage.jpg";
import avatar from "/images/avatar.png";

export const allListings = [
  {id:1,
    designTitle: "Luxury Apartment",
    location: "jalore",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 40,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 4,
    areaInSquareFeet: 1600,
    architectName: "Ankit Suthar",
    profession: "Architect",
    popular: true,
    category: "villa",
    designDes:
      "Non non irure enim officia. Est id elit nostrud laborum eiusmod proident Lorem. Nulla aliquip enim duis adipisicing fugiat. Ullamco incididunt Lorem excepteur ut nostrud minim aliqua laboris culpa incididunt ea adipisicing aliqua.",
  },
  {id:2,
    designTitle: "Luxury Apartment",
    location: "jaipur",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 40,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 4,
    areaInSquareFeet: 1600,
    architectName: "Ankit Suthar",
    profession: "Architect",
    popular: true,
    category: "zilla",
    designDes:
      "Consectetur amet enim dolore reprehenderit consequat anim incididunt fugiat laboris reprehenderit et sunt proident. Eiusmod commodo in dolor ut reprehenderit aliqua laborum do laboris non sint laborum voluptate. Velit duis nostrud fugiat laborum sit sunt quis ad esse culpa deserunt. Veniam occaecat minim proident sit cillum ipsum Lorem.",
  },
  {id:3,
    designTitle: "Luxury Apartment",
    location: "jaipur",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 40,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 4,
    areaInSquareFeet: 1600,
    architectName: "Ankit Suthar",
    profession: "Architect",
    popular: true,
    category: "villa",
    designDes:
      "Commodo enim magna qui adipisicing. Eiusmod sit eiusmod aliquip culpa deserunt et tempor non eiusmod sunt aliqua sunt consequat. Deserunt est aliquip est elit minim ipsum nisi quis adipisicing ullamco. Officia sit ipsum consequat sint consequat irure ex minim tempor aliqua et eiusmod nulla.",
  },
  {id:4,
    designTitle: "Luxury Apartment",
    location: "pune",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 40,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 4,
    areaInSquareFeet: 1600,
    architectName: "Ankit Suthar",
    profession: "Architect",
    popular: true,
    category: "milla",
    designDes:
      "Sit sit duis dolore dolore et commodo fugiat pariatur minim eu proident culpa aliquip nostrud. Pariatur et est ut nulla tempor reprehenderit. Nisi pariatur qui eiusmod anim adipisicing. Proident Lorem irure aliquip nisi id sit est nulla ex sit laboris. Do minim veniam culpa esse amet voluptate in.",
  },
  {id:5,
    designTitle: "Luxury Apartment",
    location: "sirohi",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 40,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 4,
    areaInSquareFeet: 1600,
    architectName: "Ankit Suthar",
    profession: "Architect",
    popular: true,
    category: "lilla",
    designDes:
      "Do magna sint sint ipsum exercitation. Officia ullamco excepteur laboris reprehenderit excepteur veniam nostrud ex veniam. Qui deserunt id labore dolore ad aliquip officia do amet mollit mollit cupidatat dolore.",
  },
  {id:6,
    designTitle: "Luxury Apartment",
    location: "barmer",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 40,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 4,
    areaInSquareFeet: 1600,
    architectName: "Ankit Suthar",
    profession: "Architect",
    popular: false,
    category: "gilla",
    designDes:
      "Ad in voluptate cillum esse in id aliqua irure ea nostrud nisi minim. Amet ex incididunt magna ex minim anim laboris nostrud laboris duis. Aute nostrud velit nulla ut aliqua veniam quis commodo veniam nulla. Do excepteur ad adipisicing nisi excepteur reprehenderit velit esse esse adipisicing. Consectetur est fugiat non officia aute deserunt non. Quis nulla veniam esse aliqua quis adipisicing velit ex laborum ullamco duis id enim in. Reprehenderit eiusmod incididunt ipsum nisi dolor.",
  },
  {id:7,
    designTitle: "Modern Residential House",
    location: "sirohi",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 45,
    widthInFeet: 35,
    noOfBathRooms: 4,
    noOfBedRooms: 5,
    areaInSquareFeet: 2000,
    architectName: "Ravi Sharma",
    profession: "Architect",
    popular: false,
    category: "Residential",
    designDes:
      "Velit cupidatat duis velit velit. Labore cillum ad ullamco voluptate est minim magna ut incididunt in. Ad excepteur anim enim aliquip labore duis consequat reprehenderit. Tempor anim eiusmod eiusmod aute incididunt veniam est est anim. Consectetur dolore laborum sit incididunt duis ea magna elit tempor. Eu irure anim consequat et Lorem excepteur labore tempor. Occaecat reprehenderit labore minim consectetur aliqua proident excepteur dolor proident cupidatat consequat quis nisi anim.",
  },
  {id:8,
    designTitle: "Luxury Commercial Building",
    location: "pali",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 60,
    widthInFeet: 50,
    noOfBathRooms: 8,
    noOfBedRooms: 0,
    areaInSquareFeet: 5000,
    architectName: "Meera Patel",
    profession: "Architect",
    popular: false,
    category: "Commercial Hospitality",
    designDes:
      "Officia mollit veniam veniam irure cupidatat. Nostrud dolore veniam sint consectetur anim eiusmod incididunt in voluptate dolore nostrud est ut officia. Id velit magna cupidatat dolor reprehenderit exercitation sit mollit labore.",
  },
  {id:9,
    designTitle: "Beautiful Exterior Design",
    location: "sirohi",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 50,
    widthInFeet: 45,
    noOfBathRooms: 6,
    noOfBedRooms: 4,
    areaInSquareFeet: 2200,
    architectName: "Suresh Kumar",
    profession: "Architect",
    popular: false,
    category: "Exterior",
    designDes:
      "Aute enim ea nulla velit elit eu voluptate. Incididunt irure aliqua amet occaecat labore labore pariatur ea quis. Ipsum eiusmod incididunt commodo dolore mollit. Veniam sit minim officia reprehenderit ut non cupidatat proident nostrud non laboris enim ad. Veniam qui irure laboris velit commodo nostrud fugiat excepteur sit.",
  },
  {id:10,
    designTitle: "Modern Interior Design",
    location: "jalore",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 55,
    widthInFeet: 40,
    noOfBathRooms: 5,
    noOfBedRooms: 6,
    areaInSquareFeet: 2500,
    architectName: "Neha Agarwal",
    profession: "Interior Designer",
    popular: false,
    category: "Interior",
    designDes:
      "Dolor sint dolor cupidatat elit deserunt do proident amet aliqua culpa. Et do occaecat proident consequat aliquip irure do voluptate nisi duis est cupidatat. Exercitation ut aliquip adipisicing Lorem consectetur consectetur adipisicing officia id irure sint velit velit.",
  },
  {id:11,
    designTitle: "Peaceful Temple Design",
    location: "pali",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 70,
    widthInFeet: 50,
    noOfBathRooms: 0,
    noOfBedRooms: 0,
    areaInSquareFeet: 3000,
    architectName: "Vijay Gupta",
    profession: "Architect",
    popular: false,
    category: "Temples",
    designDes:
      "Fugiat in reprehenderit do elit aliqua ex sunt consequat dolore officia anim. Fugiat incididunt qui enim id. Qui ex consequat ut incididunt. Amet labore elit culpa exercitation dolore exercitation duis mollit ut anim do. Ea laboris cillum eu sit nulla excepteur ex ea consequat est proident ea. Velit commodo aute id sunt id culpa.",
  },
  {id:12,
    designTitle: "Spacious Villa",
    location: "sirohi",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 60,
    widthInFeet: 55,
    noOfBathRooms: 6,
    noOfBedRooms: 7,
    areaInSquareFeet: 3500,
    architectName: "Kiran Reddy",
    profession: "Architect",
    popular: false,
    category: "villa",
    designDes:
      "Sit dolor ut officia irure cupidatat culpa consectetur ipsum eiusmod excepteur occaecat. Occaecat veniam sint est exercitation occaecat eu labore eu velit ad nisi. Minim ipsum veniam excepteur ea mollit.",
  },
  {id:13,
    designTitle: "Modern Apartment",
    location: "jalore",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 50,
    widthInFeet: 45,
    noOfBathRooms: 4,
    noOfBedRooms: 5,
    areaInSquareFeet: 2800,
    architectName: "Aishwarya Rao",
    profession: "Architect",
    popular: false,
    category: "Residential",
    designDes:
      "Ut proident non reprehenderit non Lorem est velit veniam non esse. Enim labore nostrud et culpa eiusmod irure sunt dolor proident labore sint. Fugiat nulla id adipisicing ut dolore pariatur labore do consectetur ex reprehenderit enim anim aliqua. Amet reprehenderit velit adipisicing do non ex incididunt esse eiusmod non cupidatat. Irure fugiat irure nulla aute adipisicing incididunt. Nostrud ut ullamco Lorem reprehenderit in eiusmod consectetur commodo dolore et. Consectetur cupidatat proident culpa deserunt sit laborum proident.",
  },
  {id:14,
    designTitle: "Luxury Hotel",
    location: "pali",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 100,
    widthInFeet: 80,
    noOfBathRooms: 20,
    noOfBedRooms: 50,
    areaInSquareFeet: 10000,
    architectName: "Rahul Mehta",
    profession: "Architect",
    popular: false,
    category: "Commercial Hospitality",
    designDes:
      "Velit voluptate tempor voluptate reprehenderit reprehenderit occaecat veniam proident duis deserunt aliquip sint proident cupidatat. Ullamco non ad aliqua est et sint pariatur est duis labore irure sunt in elit. Cupidatat duis tempor commodo nisi exercitation enim sunt culpa velit excepteur duis reprehenderit quis velit. Amet occaecat cupidatat deserunt tempor.",
  },
  {id:15,
    designTitle: "Contemporary Office Building",
    location: "barmer",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 70,
    widthInFeet: 60,
    noOfBathRooms: 10,
    noOfBedRooms: 0,
    areaInSquareFeet: 8000,
    architectName: "Pooja Shah",
    profession: "Architect",
    popular: false,
    category: "Commercial Hospitality",
    designDes:
      "Sit sunt laboris ullamco occaecat irure in dolore reprehenderit adipisicing aliqua culpa irure. Aliqua Lorem ad mollit ex aliquip reprehenderit dolor non exercitation. Ex veniam reprehenderit nisi laborum labore aliqua mollit occaecat aliqua labore anim occaecat. Aliqua ullamco ullamco incididunt nostrud. Quis mollit consequat magna aliquip ad magna eu.",
  },
  {id:16,
    designTitle: "Modern Temple Design",
    location: "jaipur",
    houseImage: house,
    allImages : [
      firstImage, secondImage, thirdImage, fourthImage, fifthImage, sixthImage, seventhImage, eighthImage
    ],
    architectImage: avatar,
    heightInFeet: 80,
    widthInFeet: 70,
    noOfBathRooms: 0,
    noOfBedRooms: 0,
    areaInSquareFeet: 4000,
    architectName: "Lakshmi Iyer",
    profession: "Architect",
    popular: true,
    category: "Temples",
    designDes:
      "Quis incididunt ipsum ipsum aliquip eu ea nostrud eiusmod deserunt. Esse sint deserunt culpa occaecat proident proident pariatur sunt aliquip est commodo nostrud. Reprehenderit esse ut quis magna pariatur. Est adipisicing deserunt aliqua ad voluptate aute voluptate est nulla irure. Lorem ex est sunt adipisicing mollit veniam nostrud nulla. Eiusmod consequat laboris officia ullamco velit. Dolore irure excepteur ex labore sint ea voluptate mollit amet.",
  },
];
